version: "3"

tasks:
  clean:
    deps: []
    cmds:
      - mvn clean

  build:
    deps: []
    sources:
      - ./src/**/*.*
      - ./pom.xml
    generates:
      - ./target/**/*.*
    cmds:
      - mvn -q -DskipTests package

  cycle:
    deps: [build]
    cmds:
      - java -jar ./target/jenkins-lsp-1.0.0-all.jar

  tests:
    deps: [build]
    cmds:
      - ./integration-tests.groovy {{.CLI_ARGS}}
